# Configuration file running Aqua locally

title = "Configuration for Aqua"

config_dir = "/Users/davideberdin/Documents/github/norman/test/"
data_dir= ""
node_name= ""
bind_addr= ""
rpc_port= ""
start_join_addrs= ""
bootstrap= false

[server_tls]
cert_file = "certs/server.pem"
key_file= "certs/server-key.pem"
ca_file= "certs/ca.pem"
    
[peer_tls]
cert_file = "certs/client.pem"
key_file= "certs/client-key.pem"
ca_file= "certs/ca.pem"
