# Configuration file running Norman locally

[commander]
address = "127.0.0.1"
port = 8080

[broker]
address = "127.0.0.1"
port = 8081

[storage]
address = "127.0.0.1"
port = 8082
bind_addr= ""
rpc_port= ""


[logger]
level = "trace"
pretty = true