# Configuration file running the Norman locally

title = "Configuration for the Norman"
config_dir = "/Users/davideberdin/Documents/github/norman/test/"

[commander]
address = "127.0.0.1"
port = 8080

    [commander.aqua]
    cafile = "certs/ca.pem"
    server_cert_file = "certs/server.pem"
    server_key_file = "certs/server-key.pem"
    root_client_cert_file = "certs/root-client.pem"
    root_client_key_file = "certs/root-client-key.pem"
    nobody_client_cert_file = "certs/nobody-client.pem"
    nobody_client_key_file = "certs/nobody-client-key.pem"

[broker]
address = "127.0.0.1"
port = 8081

[storage]
address = "127.0.0.1"
port = 8082

    [storage.deep_storage]
    type = "s3"
    bucket = "test-deep-storage"

[logger]
level = "trace"
pretty = true