basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is the swagger definition of the Commander APIs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Commander API
  version: v0.0.1
paths: {}
swagger: "2.0"
